- name: Build the components for an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        state: present
        name: Testing
        location: westus
        tags:
          testing: testing
          delete: never

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: Testing
        name: testvn001
        address_prefixes: "10.10.0.0/16"
        state: "{{ state }}"

    - name: Add subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: Testing
        name: subnet001
        address_prefix: "10.10.0.0/24"
        virtual_network: testvn001
        state: "{{ state }}"

    - name: Create public ip
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: Testing
        allocation_method: Static
        name: publicip001
        state: "{{ state }}"

    - name: Create security group that allows SSH
      azure.azcollection.azure_rm_securitygroup:
        resource_group: Testing
        name: secgroup001
        state: "{{ state }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound

    - name: Create NIC
      azure.azcollection.azure_rm_networkinterface:
        resource_group: Testing
        name: testnic001
        state: "{{ state }}"
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: publicip001
        security_group: secgroup001

    - name: Create virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: Testing
        name: testvm001
        state: "{{ state }}"
        vm_size: Standard_B1s   # for a list see --> https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2
        managed_disk_type: Standard_LRS
        admin_username: bruce_wayne
        admin_password: GoAlta3!
        network_interfaces: testnic001
        # for list of images see --> https://az-vm-image.info/
        image:
          offer: debian-11
          publisher: Debian
          sku: 11-backports-gen2   # this is a "gen 2 image"
          version: latest

