- name: Build the components for an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        state: present
        name: "{{ rg_name }}"
        location: "{{ location }}"
        tags: "{{ tags }}"

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ rg_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "{{ address_prefixes }}"
        state: present

    - name: Add subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ rg_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ address_prefix }}"
        virtual_network: "{{ vnet_name }}"
        state: present

    - name: Create public ip
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ rg_name }}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
        state: present

    - name: Create security group that allows SSH
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ rg_name }}"
        name: secgroup001
        state: present
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound

    - name: Create NIC
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ rg_name }}"
        name: testnic001
        state: present
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"
        security_group: secgroup001

    - name: Create virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ rg_name }}"
        name: "{{ vm_name }}"
        state: present
        vm_size: "{{ vm_size }}"   # for a list see --> https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2
        managed_disk_type: Standard_LRS
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: testnic001
        image: "{{ image }}"
