- name: Build the components for an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    build_action: present  # default

  tasks:

  - name: deploy azure VM
    ansible.builtin.import_tasks:
      file: tasks/deploy_azure_vm.yml
    when: build_action == "present"

  - name: deploy azure VM
    ansible.builtin.import_tasks:
      file: tasks/remove_azure_vm.yml
    when: build_action == "absent"

